const image = (id, url, alt, position) => ({
  id,
  type: 'IMAGE',
  url,
  alt,
  position,
});

const photoUrl = (id) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=82`;

export const EXAMPLE_PROPERTIES = [
  {
    id: 'home-example-chico',
    isExample: true,
    title: 'Apartamento luminoso en Chico Norte',
    summary: 'Espacios amplios, balcon y conexion rapida con oficinas, comercio y parques.',
    description:
      'Apartamento de dos habitaciones con sala comedor amplia, cocina integral abierta y balcon con buena entrada de luz natural. La propiedad esta pensada para profesionales o parejas que buscan una ubicacion tranquila, con porteria y acceso facil a transporte, supermercados y zonas de trabajo.',
    propertyType: 'APARTMENT',
    department: 'Bogota D.C.',
    city: 'Bogota',
    neighborhood: 'Chico Norte',
    addressLine: 'Calle 93 con Carrera 18',
    zoneReference: 'A pocos minutos del Parque de la 93',
    hideExactAddress: true,
    monthlyRent: 3200000,
    maintenanceFee: 280000,
    securityDeposit: 3200000,
    bedrooms: 2,
    bathrooms: 2,
    areaM2: 72,
    floor: 6,
    strata: 5,
    parkingSpots: 1,
    balcony: true,
    elevator: true,
    security: true,
    doorman: true,
    commonAreas: true,
    equippedKitchen: true,
    laundryArea: true,
    furnished: false,
    petsAllowed: true,
    availableImmediately: true,
    minLeaseMonths: 12,
    depositRequired: true,
    administrationIncluded: false,
    acceptsFamilies: true,
    acceptsStudents: false,
    acceptsCosigner: true,
    requiresRentalStudy: true,
    visitsAllowed: true,
    visitHours: 'Lunes a sabado, 9:00 a.m. a 5:00 p.m.',
    contactHours: 'Respuesta usual entre 8:00 a.m. y 6:00 p.m.',
    amenities: ['Cocina integral', 'Zona de ropas', 'Porteria', 'Ascensor', 'Balcon', 'Parqueadero cubierto'],
    servicesIncluded: [],
    rules: 'No se permiten fiestas. Mascotas pequenas sujetas a aprobacion del conjunto.',
    requirements: 'Estudio de arriendo, certificacion laboral y documento de identidad.',
    idealTenantProfile: 'Pareja o profesional que valore una zona residencial con buena movilidad.',
    specialConditions: 'Contrato minimo de un ano.',
    verificationDetails: 'Propiedad verificada por NIDO con informacion de contacto validada.',
    rating: 4.8,
    averageRating: 4.8,
    reviewsCount: 12,
    commentsCount: 12,
    coverImage: photoUrl('photo-1502672260266-1c1ef2d93688'),
    images: [
      image('chico-1', photoUrl('photo-1502672260266-1c1ef2d93688'), 'Sala luminosa de apartamento en Chico Norte', 0),
      image('chico-2', photoUrl('photo-1560448204-e02f11c3d0e2'), 'Habitacion principal con luz natural', 1),
      image('chico-3', photoUrl('photo-1556909114-f6e7ad7d3136'), 'Cocina integral abierta', 2),
      image('chico-4', photoUrl('photo-1522708323590-d24dbb6b0267'), 'Zona social con acabados modernos', 3),
      image('chico-5', photoUrl('photo-1484154218962-a197022b5858'), 'Bano claro y funcional', 4),
    ],
    owner: {
      fullName: 'Camila Restrepo',
      name: 'Camila Restrepo',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80',
      bio: 'Arrendadora verificada con experiencia administrando vivienda residencial en el norte de Bogota.',
      responseRate: '98%',
      responseTime: 'Responde en menos de 2 horas',
      verified: true,
      createdAt: '2024-03-12',
    },
    reviews: [
      {
        id: 'chico-review-1',
        userName: 'Laura M.',
        rating: 5,
        comment: 'Muy buena ubicacion, el apartamento estaba limpio y la comunicacion fue rapida.',
        date: '2026-03-04',
        createdAt: '2026-03-04',
      },
      {
        id: 'chico-review-2',
        userName: 'Andres R.',
        rating: 4.7,
        comment: 'La zona es tranquila y el edificio se siente seguro. Las fotos coincidian con la visita.',
        date: '2026-02-18',
        createdAt: '2026-02-18',
      },
    ],
    comments: [
      {
        id: 'chico-comment-1',
        userName: 'Laura M.',
        rating: 5,
        comment: 'Muy buena ubicacion, el apartamento estaba limpio y la comunicacion fue rapida.',
        createdAt: '2026-03-04',
      },
      {
        id: 'chico-comment-2',
        userName: 'Andres R.',
        rating: 4.7,
        comment: 'La zona es tranquila y el edificio se siente seguro. Las fotos coincidian con la visita.',
        createdAt: '2026-02-18',
      },
    ],
    publishedAt: '2026-03-01',
    createdAt: '2026-02-24',
  },
  {
    id: 'home-example-envigado',
    isExample: true,
    title: 'Casa familiar con patio en Envigado',
    summary: 'Zona tranquila, buena iluminacion natural y espacios pensados para familias.',
    description:
      'Casa de tres habitaciones con patio privado, cocina amplia y estudio independiente. Esta ubicada en un sector residencial de Envigado con calles tranquilas, buena oferta de comercio barrial y rutas cercanas hacia Medellin. Ideal para familias que necesitan area social generosa y parqueadero doble.',
    propertyType: 'HOUSE',
    department: 'Antioquia',
    city: 'Envigado',
    neighborhood: 'La Magnolia',
    addressLine: 'Sector La Magnolia',
    zoneReference: 'Cerca al parque principal de Envigado',
    hideExactAddress: true,
    monthlyRent: 4100000,
    maintenanceFee: 0,
    securityDeposit: 4100000,
    bedrooms: 3,
    bathrooms: 3,
    areaM2: 128,
    floor: 1,
    strata: 4,
    parkingSpots: 2,
    balcony: false,
    elevator: false,
    security: false,
    doorman: false,
    commonAreas: false,
    equippedKitchen: true,
    laundryArea: true,
    furnished: false,
    petsAllowed: true,
    availableImmediately: false,
    availableFrom: '2026-06-15',
    minLeaseMonths: 12,
    depositRequired: true,
    administrationIncluded: true,
    acceptsFamilies: true,
    acceptsStudents: false,
    acceptsCosigner: true,
    requiresRentalStudy: true,
    visitsAllowed: true,
    visitHours: 'Martes, jueves y sabado con cita previa.',
    contactHours: 'Respuesta usual en la manana.',
    amenities: ['Patio privado', 'Cocina integral', 'Zona de ropas', 'Estudio', 'Parqueadero doble', 'Pet friendly'],
    servicesIncluded: [],
    rules: 'Mascotas permitidas con manejo responsable del patio.',
    requirements: 'Estudio de arriendo y soporte de ingresos.',
    idealTenantProfile: 'Familia que busque una vivienda amplia en zona residencial.',
    specialConditions: 'Disponible desde el 15 de junio de 2026.',
    verificationDetails: 'Propiedad verificada por NIDO con disponibilidad confirmada.',
    rating: 4.7,
    averageRating: 4.7,
    reviewsCount: 9,
    commentsCount: 9,
    coverImage: photoUrl('photo-1600585154340-be6161a56a0c'),
    images: [
      image('envigado-1', photoUrl('photo-1600585154340-be6161a56a0c'), 'Fachada de casa familiar en Envigado', 0),
      image('envigado-2', photoUrl('photo-1600566753190-17f0baa2a6c3'), 'Sala amplia de casa familiar', 1),
      image('envigado-3', photoUrl('photo-1600566753086-00f18fb6b3ea'), 'Cocina y comedor integrados', 2),
      image('envigado-4', photoUrl('photo-1600573472592-401b489a3cdc'), 'Habitacion principal de casa', 3),
      image('envigado-5', photoUrl('photo-1600607687939-ce8a6c25118c'), 'Patio privado con luz natural', 4),
    ],
    owner: {
      fullName: 'Felipe Alvarez',
      name: 'Felipe Alvarez',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80',
      bio: 'Propietario local con atencion directa y procesos claros de visita.',
      responseRate: '95%',
      responseTime: 'Responde durante el mismo dia',
      verified: true,
      createdAt: '2023-11-08',
    },
    reviews: [
      {
        id: 'envigado-review-1',
        userName: 'Juliana P.',
        rating: 4.8,
        comment: 'La casa es amplia y el barrio se siente muy familiar. El propietario fue puntual.',
        date: '2026-04-12',
        createdAt: '2026-04-12',
      },
      {
        id: 'envigado-review-2',
        userName: 'Mario C.',
        rating: 4.6,
        comment: 'Buen patio y parqueadero comodo. La informacion de costos fue clara desde el inicio.',
        date: '2026-01-27',
        createdAt: '2026-01-27',
      },
    ],
    comments: [
      {
        id: 'envigado-comment-1',
        userName: 'Juliana P.',
        rating: 4.8,
        comment: 'La casa es amplia y el barrio se siente muy familiar. El propietario fue puntual.',
        createdAt: '2026-04-12',
      },
      {
        id: 'envigado-comment-2',
        userName: 'Mario C.',
        rating: 4.6,
        comment: 'Buen patio y parqueadero comodo. La informacion de costos fue clara desde el inicio.',
        createdAt: '2026-01-27',
      },
    ],
    publishedAt: '2026-04-08',
    createdAt: '2026-04-03',
  },
  {
    id: 'home-example-studio',
    isExample: true,
    title: 'Apartaestudio amoblado en Granada',
    summary: 'Ideal para una persona, con servicios cercanos y mantenimiento simple.',
    description:
      'Apartaestudio amoblado con distribucion eficiente, cocina equipada y zona de descanso independiente. Esta cerca de restaurantes, servicios y transporte, por lo que funciona bien para una persona que quiere mudarse con poco mobiliario y costos previsibles.',
    propertyType: 'STUDIO',
    department: 'Valle del Cauca',
    city: 'Cali',
    neighborhood: 'Granada',
    addressLine: 'Avenida 9N, sector Granada',
    zoneReference: 'Cerca a la zona gastronomica de Granada',
    hideExactAddress: true,
    monthlyRent: 1850000,
    maintenanceFee: 160000,
    securityDeposit: 1850000,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 38,
    floor: 4,
    strata: 5,
    parkingSpots: 0,
    balcony: false,
    elevator: true,
    security: true,
    doorman: true,
    commonAreas: true,
    equippedKitchen: true,
    laundryArea: true,
    furnished: true,
    petsAllowed: false,
    utilitiesIncluded: true,
    availableImmediately: true,
    minLeaseMonths: 6,
    depositRequired: true,
    administrationIncluded: false,
    acceptsFamilies: false,
    acceptsStudents: true,
    acceptsCosigner: true,
    requiresRentalStudy: true,
    visitsAllowed: true,
    visitHours: 'Con cita previa entre semana.',
    contactHours: 'Respuesta usual en menos de 3 horas.',
    amenities: ['Amoblado', 'Cocina equipada', 'Internet incluido', 'Lavanderia comunal', 'Ascensor', 'Vigilancia'],
    servicesIncluded: ['Internet', 'Agua'],
    rules: 'No se permiten mascotas ni eventos.',
    requirements: 'Documento de identidad, soporte de ingresos y referencia personal.',
    idealTenantProfile: 'Profesional, estudiante de posgrado o persona que viva sola.',
    specialConditions: 'Contrato minimo de seis meses.',
    verificationDetails: 'Propiedad verificada por NIDO con mobiliario registrado.',
    rating: 4.6,
    averageRating: 4.6,
    reviewsCount: 7,
    commentsCount: 7,
    coverImage: photoUrl('photo-1524758631624-e2822e304c36'),
    images: [
      image('studio-1', photoUrl('photo-1524758631624-e2822e304c36'), 'Apartaestudio amoblado en Granada', 0),
      image('studio-2', photoUrl('photo-1505693416388-ac5ce068fe85'), 'Zona de descanso amoblada', 1),
      image('studio-3', photoUrl('photo-1556911220-bff31c812dba'), 'Cocina compacta equipada', 2),
      image('studio-4', photoUrl('photo-1560185127-6ed189bf02f4'), 'Espacio social del apartaestudio', 3),
      image('studio-5', photoUrl('photo-1584622650111-993a426fbf0a'), 'Bano de apartaestudio', 4),
    ],
    owner: {
      fullName: 'Natalia Gomez',
      name: 'Natalia Gomez',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=240&q=80',
      bio: 'Arrendadora verificada, enfocada en contratos claros para estadias de mediano plazo.',
      responseRate: '97%',
      responseTime: 'Responde en menos de 3 horas',
      verified: true,
      createdAt: '2024-08-21',
    },
    reviews: [
      {
        id: 'studio-review-1',
        userName: 'Sofia G.',
        rating: 4.5,
        comment: 'El apartaestudio estaba bien equipado y la zona es comoda para moverse sin carro.',
        date: '2026-03-21',
        createdAt: '2026-03-21',
      },
      {
        id: 'studio-review-2',
        userName: 'Daniel V.',
        rating: 4.7,
        comment: 'La informacion de servicios incluidos fue clara. Buena opcion para vivir solo.',
        date: '2026-02-09',
        createdAt: '2026-02-09',
      },
    ],
    comments: [
      {
        id: 'studio-comment-1',
        userName: 'Sofia G.',
        rating: 4.5,
        comment: 'El apartaestudio estaba bien equipado y la zona es comoda para moverse sin carro.',
        createdAt: '2026-03-21',
      },
      {
        id: 'studio-comment-2',
        userName: 'Daniel V.',
        rating: 4.7,
        comment: 'La informacion de servicios incluidos fue clara. Buena opcion para vivir solo.',
        createdAt: '2026-02-09',
      },
    ],
    publishedAt: '2026-03-15',
    createdAt: '2026-03-10',
  },
  {
    id: 'home-example-room',
    isExample: true,
    title: 'Habitacion amoblada en Alto Prado',
    summary: 'Opcion flexible cerca a transporte, universidades y zonas de servicios.',
    description:
      'Habitacion privada amoblada dentro de vivienda compartida, con acceso a cocina, sala y zona de ropas. Es una opcion practica para estudiantes o profesionales que buscan un arriendo flexible, con buena ubicacion y reglas de convivencia claras.',
    propertyType: 'ROOM',
    department: 'Atlantico',
    city: 'Barranquilla',
    neighborhood: 'Alto Prado',
    addressLine: 'Sector Alto Prado',
    zoneReference: 'Cerca a rutas de transporte y servicios',
    hideExactAddress: true,
    monthlyRent: 980000,
    maintenanceFee: 0,
    securityDeposit: 980000,
    bedrooms: 1,
    bathrooms: 1,
    areaM2: 18,
    floor: 2,
    strata: 5,
    parkingSpots: 0,
    balcony: false,
    elevator: false,
    security: true,
    doorman: false,
    commonAreas: true,
    equippedKitchen: true,
    laundryArea: true,
    furnished: true,
    petsAllowed: false,
    utilitiesIncluded: true,
    availableImmediately: true,
    minLeaseMonths: 4,
    depositRequired: true,
    administrationIncluded: true,
    acceptsFamilies: false,
    acceptsStudents: true,
    acceptsCosigner: false,
    requiresRentalStudy: false,
    visitsAllowed: true,
    visitHours: 'Tardes con cita previa.',
    contactHours: 'Respuesta usual en horario laboral.',
    amenities: ['Habitacion amoblada', 'Cocina compartida', 'Zona de ropas', 'Internet incluido', 'Servicios incluidos'],
    servicesIncluded: ['Internet', 'Agua', 'Energia'],
    rules: 'Ambientes tranquilos, no fumadores y visitas coordinadas previamente.',
    requirements: 'Documento de identidad y referencia personal.',
    idealTenantProfile: 'Estudiante o profesional joven con rutinas tranquilas.',
    specialConditions: 'Contrato flexible desde cuatro meses.',
    verificationDetails: 'Propiedad verificada por NIDO con reglas de convivencia visibles.',
    rating: 4.5,
    averageRating: 4.5,
    reviewsCount: 5,
    commentsCount: 5,
    coverImage: photoUrl('photo-1560448204-61dc36dc98c8'),
    images: [
      image('room-1', photoUrl('photo-1560448204-61dc36dc98c8'), 'Habitacion amoblada en Alto Prado', 0),
      image('room-2', photoUrl('photo-1505693416388-ac5ce068fe85'), 'Cama y escritorio de habitacion', 1),
      image('room-3', photoUrl('photo-1556911220-bff31c812dba'), 'Cocina compartida equipada', 2),
      image('room-4', photoUrl('photo-1560185127-6ed189bf02f4'), 'Sala compartida de vivienda', 3),
      image('room-5', photoUrl('photo-1493809842364-78817add7ffb'), 'Ambiente interior compartido', 4),
    ],
    owner: {
      fullName: 'Monica Perez',
      name: 'Monica Perez',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=240&q=80',
      bio: 'Anfitriona verificada con experiencia en vivienda compartida para estudiantes.',
      responseRate: '94%',
      responseTime: 'Responde durante el dia',
      verified: true,
      createdAt: '2025-01-16',
    },
    reviews: [
      {
        id: 'room-review-1',
        userName: 'Paula C.',
        rating: 4.6,
        comment: 'La habitacion era tal como se veia en las fotos y las reglas estaban claras.',
        date: '2026-04-02',
        createdAt: '2026-04-02',
      },
      {
        id: 'room-review-2',
        userName: 'Esteban N.',
        rating: 4.4,
        comment: 'Buena ubicacion y comunicacion amable. Me gusto que los servicios estuvieran incluidos.',
        date: '2026-02-14',
        createdAt: '2026-02-14',
      },
    ],
    comments: [
      {
        id: 'room-comment-1',
        userName: 'Paula C.',
        rating: 4.6,
        comment: 'La habitacion era tal como se veia en las fotos y las reglas estaban claras.',
        createdAt: '2026-04-02',
      },
      {
        id: 'room-comment-2',
        userName: 'Esteban N.',
        rating: 4.4,
        comment: 'Buena ubicacion y comunicacion amable. Me gusto que los servicios estuvieran incluidos.',
        createdAt: '2026-02-14',
      },
    ],
    publishedAt: '2026-03-28',
    createdAt: '2026-03-20',
  },
];

export const findExamplePropertyById = (propertyId) =>
  EXAMPLE_PROPERTIES.find((property) => property.id === propertyId) || null;

export const getSimilarExampleProperties = (property, limit = 3) => {
  if (!property) {
    return EXAMPLE_PROPERTIES.slice(0, limit);
  }

  const byCityOrType = EXAMPLE_PROPERTIES.filter(
    (item) =>
      item.id !== property.id &&
      (item.city === property.city || item.propertyType === property.propertyType)
  );
  const fallback = EXAMPLE_PROPERTIES.filter((item) => item.id !== property.id);

  return (byCityOrType.length ? byCityOrType : fallback).slice(0, limit);
};
